<?php
    $taglist = [
        'centos',
        'fedora',
        'ubuntu',
        'debian',
        'nginx',
        'apache',
        'nextcloud',
        'nodejs',
        'mongodb',
        'chromeos',
        'letsencrypt',
        'netcore',
        'natale',
        'vestacp',
        'python',
        'php',
        'github',
        'arch linux',
        'gnome',
        'rhel',
        'ssh',
    ]
?>
